### ISSUE TITLE
Widget margin

### ISSUE THREAD

**Issue by pdwinkel** [patbuergin/angular-widget-grid#6]
Great library!
Is there a way to specify a margin around the widgets?
Let say, 5px space between the widgets.

**Comment by patbuergin** [comment]
Thanks!

I can't think of a trivial way to add a margin to the widgets, but you can achieve a similar look by adding a padding for the widget content. The following rule should do:
```css
.wg-widget-content {
    width: initial;
    height: initial;
    top: 3px;
    right: 3px;
    bottom: 3px;
    left: 3px;
}
```

You can find the existing rule for that class [here](https://github.com/patbuergin/angular-widget-grid/blob/master/src/css/angular-widget-grid.css#L11-L18).
